### ISSUE TITLE
Problem after authenticating

### ISSUE THREAD

**Issue by AliAliyev17** [egefeyzioglu/mymedia-download#3]
Hi Ege. Thank you for this great tool. I had an issue during running it, where after I successfully authenticated, during collection of video urls it threw this error at me.

```
Authenticated. Collecting video URLs... Traceback (most recent call last):
File "C:\Users\alial\Downloads\mymedia-downloader.py", line 79, in <module>
    driver.get(url)
  File "C:\Users\alial\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 449, in get
    self.execute(Command.GET, {"url": url})
  File "C:\Users\alial\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 440, in execute
    self.error_handler.check_response(response)
  File "C:\Users\alial\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 245, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.InvalidArgumentException: Message: invalid argument
  (Session info: headless chrome=119.0.6045.200)
Stacktrace:
        GetHandleVerifier [0x004F72A3+45731]
        (No symbol) [0x00482D51]
        (No symbol) [0x003786D0]
        (No symbol) [0x0036AFEB]
        (No symbol) [0x003698EE]
        (No symbol) [0x00369ED8]
        (No symbol) [0x0037A5B3]
        (No symbol) [0x003DBD41]
        (No symbol) [0x003C7FDC]
        (No symbol) [0x003DB7A2]
        (No symbol) [0x003C7DD6]
        (No symbol) [0x003A31F6]
        (No symbol) [0x003A439D]
        GetHandleVerifier [0x00800716+3229462]
        GetHandleVerifier [0x008484C8+3523784]
        GetHandleVerifier [0x0084214C+3498316]
        GetHandleVerifier [0x00581680+611968]
        (No symbol) [0x0048CCCC]
        (No symbol) [0x00488DF8]
        (No symbol) [0x00488F1D]
        (No symbol) [0x0047B2C7]
        BaseThreadInitThunk [0x75517BA9+25]
       RtlInitializeExceptionChain [0x7765BD2B+107]
       RtlClearBits [0x7765BCAF+191]
```

**Comment by egefeyzioglu** [comment]
Sorry for the delay, just fixed this. Please lmk if you're still having issues with the tool
